# Gradle
org.gradle.jvmargs=-Xmx3G \
  --enable-native-access=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.20-beta
neo_version_range=[26.1.2,26.1.3)
loader_version_range=[1,)

# Mod Properties
mod_id=registrylib
mod_name=registrylib
mod_license=MPL-2.0
mod_group_id=net.ptcrys
mod_authors=suried
mod_description=A registry library mod for Minecraft.


