package net.phasetranscrystal.registrylib;

import net.phasetranscrystal.registrylib.annotations.StandardAPI;
import net.phasetranscrystal.registrylib.builders.BlockBuilder;
import net.phasetranscrystal.registrylib.builders.BlockEntityBuilder;
import net.phasetranscrystal.registrylib.builders.FluidBuilder;
import net.phasetranscrystal.registrylib.builders.ItemBuilder;
import net.phasetranscrystal.registrylib.datagen.ProviderType;
import net.phasetranscrystal.registrylib.datagen.provider.RegistryLibLangProvider;
import net.phasetranscrystal.registrylib.datagen.provider.RegistryLibTagsProvider;

import net.minecraft.data.tags.TagsProvider;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Fluid;
import net.neoforged.neoforge.fluids.BaseFlowingFluid;

import it.unimi.dsi.fastutil.objects.Reference2BooleanOpenHashMap;
import it.unimi.dsi.fastutil.objects.Reference2ReferenceOpenHashMap;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.NotNull;

import java.util.function.Function;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;

import javax.annotation.Nullable;

/**
 * A lightweight grouping wrapper around {@link RegistryCore} that applies shared defaults (creative
 * tab, property modifiers, lang prefix) to all entries created through it.
 *
 * <p>
 * The group name is used to automatically derive a {@code langPrefix}: {@code "machines"}
 * becomes {@code "Machines"}, which is prepended to every entry's display name. You can override
 * this with an explicit {@link Builder#langPrefix(String)} call.
 *
 * <p>
 * {@link Builder#tab(ResourceKey)} applies to <em>all</em> item-like sub-resources: standalone
 * items, block items generated by {@code .simpleItem()}/{@code .item()}, and fluid buckets.
 *
 * <p>
 * Construct via {@link RegistryCore#group(String)}:
 *
 * <pre>{@code
 * 
 * Group MACHINES = REGISTRYLIB.group("machines")  // langPrefix "Machines" auto-derived
 *         .tab(MACHINE_TAB)                       // applied to Item, BlockItem, and Bucket
 *         .blockProperties(p -> p.strength(3.5F))
 *         .build();
 *
 * BlockEntry<Block> CRUSHER = MACHINES.block("crusher", Block::new)
 *         .simpleItem()
 *         .register();
 * }</pre>
 */
public class Group {

    protected final RegistryCore core;
    @Nullable
    protected final ResourceKey<CreativeModeTab> tab;
    @Nullable
    protected final String langPrefix;

    @Nullable
    protected final Supplier<BlockBehaviour.Properties> initialBlockProperties;

    @Nullable
    protected final Supplier<Item.Properties> initialItemProperties;

    @Nullable
    protected final UnaryOperator<BlockBehaviour.Properties> blockPropertiesModifier;

    @Nullable
    protected final UnaryOperator<Item.Properties> itemPropertiesModifier;

    protected final Reference2ReferenceOpenHashMap<ProviderType<? extends RegistryLibTagsProvider<?>>, Reference2BooleanOpenHashMap<TagKey<?>>> tagsByType;

    protected Group(Builder builder) {
        this.core = builder.core;
        this.tab = builder.tab;
        this.langPrefix = builder.langPrefix;
        this.initialBlockProperties = builder.initialBlockProperties;
        this.initialItemProperties = builder.initialItemProperties;
        this.blockPropertiesModifier = builder.blockProperties;
        this.itemPropertiesModifier = builder.itemProperties;
        this.tagsByType = builder.tagsByType;
    }

    // === Accessors ===

    public RegistryCore getRegistryLib() {
        return core;
    }

    // === Factory Methods ===

    @StandardAPI("Returns a BlockBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends Block> BlockBuilder<T, Group> block(
                                                          String name, Function<BlockBehaviour.Properties, T> factory) {
        return applyBlockDefaults(core.block(this, name, factory));
    }

    public <T extends Item> ItemBuilder<T, Group> item(
                                                       String name, Function<Item.Properties, T> factory) {
        return applyItemDefaults(core.item(this, name, factory, false));
    }

    @StandardAPI("Returns an ItemBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends Item> ItemBuilder<T, Group> item(
                                                       String name, Function<Item.Properties, T> factory, boolean isComponentItem) {
        return applyItemDefaults(core.item(this, name, factory, isComponentItem));
    }

    @StandardAPI("Returns a BlockEntityBuilder with group defaults applied. Call .register() to finalise.")
    public <T extends BlockEntity> BlockEntityBuilder<T, Group> blockEntity(
                                                                            String name, BlockEntityBuilder.BlockEntityFactory<T> factory) {
        return core.blockEntity(this, name, factory);
    }

    @StandardAPI("Returns a FluidBuilder with group defaults applied. Call .register() to finalise.")
    public FluidBuilder<BaseFlowingFluid.Flowing, Group> fluid(
                                                               String name, Identifier stillTexture, Identifier flowingTexture) {
        return applyFluidDefaults(
                core.fluid(this, name, stillTexture, flowingTexture, BaseFlowingFluid.Flowing::new));
    }

    @StandardAPI("Returns a FluidBuilder with custom FluidFactory and group defaults applied. Call .register() to finalise.")
    public <T extends BaseFlowingFluid> FluidBuilder<T, Group> fluid(
                                                                     String name,
                                                                     Identifier stillTexture,
                                                                     Identifier flowingTexture,
                                                                     FluidBuilder.FluidFactory<T> fluidFactory) {
        return applyFluidDefaults(core.fluid(this, name, stillTexture, flowingTexture, fluidFactory));
    }

    // === Default Application ===

    @SuppressWarnings("unchecked")
    private <T extends Block> BlockBuilder<T, Group> applyBlockDefaults(
                                                                        BlockBuilder<T, Group> builder) {
        if (initialBlockProperties != null) {
            builder.setInitialProperties(initialBlockProperties);
        }
        if (blockPropertiesModifier != null) {
            builder.properties(blockPropertiesModifier);
        }
        if (tab != null) {
            builder.defaultItemTab(tab);
        }
        if (langPrefix != null) {
            builder.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        if (tagsByType != null) {
            var blockTags = tagsByType.get(ProviderType.BLOCK_TAGS);
            if (blockTags != null) {
                blockTags.forEach(
                        (tag, value) -> builder.addTag(ProviderType.BLOCK_TAGS, value, (TagKey<Block>) tag));
            }
            var itemTags = tagsByType.get(ProviderType.ITEM_TAGS);
            if (itemTags != null) {
                itemTags.forEach(
                        (tag, value) -> builder.addTag(ProviderType.ITEM_TAGS, value, (TagKey<Item>) tag));
            }
        }
        return builder;
    }

    @SuppressWarnings("unchecked")
    private <T extends Item> ItemBuilder<T, Group> applyItemDefaults(ItemBuilder<T, Group> builder) {
        if (initialItemProperties != null) {
            builder.initialProperties(initialItemProperties);
        }
        if (itemPropertiesModifier != null) {
            builder.properties(itemPropertiesModifier);
        }
        if (tab != null) {
            builder.addTab(tab);
        }
        if (langPrefix != null) {
            builder.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        if (tagsByType != null) {
            var itemTags = tagsByType.get(ProviderType.ITEM_TAGS);
            if (itemTags != null) {
                itemTags.forEach(
                        (tag, value) -> builder.addTag(ProviderType.ITEM_TAGS, value, (TagKey<Item>) tag));
            }
        }
        return builder;
    }

    @SuppressWarnings("unchecked")
    private <T extends BaseFlowingFluid> FluidBuilder<T, Group> applyFluidDefaults(
                                                                                   FluidBuilder<T, Group> builder) {
        if (tab != null) {
            builder.defaultBucketTab(tab);
        }
        if (langPrefix != null) {
            builder.lang(langPrefix + " " + RegistryLibLangProvider.toEnglishName(builder.getName()));
        }
        if (tagsByType != null) {
            var fluidTags = tagsByType.get(ProviderType.FLUID_TAGS);
            if (fluidTags != null) {
                fluidTags.forEach(
                        (tag, value) -> builder.addTag(ProviderType.FLUID_TAGS, value, (TagKey<Fluid>) tag));
            }
        }
        return builder;
    }

    // === Builder ===

    @Accessors(fluent = true, chain = true)
    public static class Builder {

        protected final RegistryCore core;
        @Nullable
        protected String langPrefix;
        @Nullable
        @Setter
        protected ResourceKey<CreativeModeTab> tab;

        protected Supplier<BlockBehaviour.Properties> initialBlockProperties;

        @Setter
        protected Supplier<Item.Properties> initialItemProperties;

        @Setter
        protected UnaryOperator<BlockBehaviour.Properties> blockProperties;

        @Setter
        protected UnaryOperator<Item.Properties> itemProperties;

        protected final Reference2ReferenceOpenHashMap<ProviderType<? extends RegistryLibTagsProvider<?>>, Reference2BooleanOpenHashMap<TagKey<?>>> tagsByType;

        protected Builder(RegistryCore core, String name) {
            this.core = core;
            this.langPrefix = core.doDatagen() ? RegistryLibLangProvider.toEnglishName(name) : null;
            this.tagsByType = core.doDatagen() ? new Reference2ReferenceOpenHashMap<>() : null;
        }

        @StandardAPI
        public Builder initialBlockProperties(Supplier<? extends Block> block) {
            initialBlockProperties = () -> BlockBehaviour.Properties.ofFullCopy(block.get());
            return this;
        }

        @StandardAPI
        public Builder initialBlockProperties(Block block) {
            initialBlockProperties = () -> BlockBehaviour.Properties.ofFullCopy(block);
            return this;
        }

        /**
         * Overrides the lang prefix auto-derived from the group name. By default, the group name is
         * converted to title case and used as the prefix (e.g. {@code "machines"} → {@code
         * "Machines"}).
         */
        @StandardAPI
        public Builder langPrefix(String prefix) {
            if (core.doDatagen()) {
                this.langPrefix = prefix;
            }
            return this;
        }

        @SafeVarargs
        @StandardAPI
        public final <R, TP extends TagsProvider<R> & RegistryLibTagsProvider<R>> Builder addTag(
                                                                                                 @NotNull ProviderType<? extends TP> type, boolean isOptional, @NotNull TagKey<R>... tags) {
            if (tagsByType != null) {
                var map = tagsByType.computeIfAbsent(type, _ -> new Reference2BooleanOpenHashMap<>());
                for (TagKey<R> tag : tags) {
                    map.put(tag, isOptional);
                }
            }
            return this;
        }

        @SafeVarargs
        public final Builder addItemTag(TagKey<Item>... tag) {
            return addTag(ProviderType.ITEM_TAGS, false, tag);
        }

        @SafeVarargs
        public final Builder addBlockTag(TagKey<Block>... tag) {
            return addTag(ProviderType.BLOCK_TAGS, false, tag);
        }

        @SafeVarargs
        public final Builder addFluidTag(TagKey<Fluid>... tag) {
            return addTag(ProviderType.FLUID_TAGS, false, tag);
        }

        @StandardAPI
        public Group build() {
            return new Group(this);
        }
    }
}
